name: Deploy to Heroku

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm install
      - name: Run tests
        run: npm test
        env:
          PORT: 3000

  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: NPM install
        run: npm install
      - name: Build app
        run: npm run build
      - name: Deploy to Heroku
        uses: AkhileshNS/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_TOKEN }}
          heroku_email: wojciech.sromek@gmail.com
          heroku_app_name: nodesii-api-ws